# Generated by Django 4.0 on 2024-10-17 01:31

import assets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('img', models.ImageField(upload_to=assets.models.upload_game_img)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Assets Game',
                'verbose_name_plural': 'Assets Game',
                'db_table': 'assets_game',
                'ordering': ('sort',),
            },
        ),
        migrations.AddField(
            model_name='assetstoken',
            name='epal',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.upload_token_epal),
        ),
        migrations.AddField(
            model_name='assetstoken',
            name='initial_buy_number',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='assetstoken',
            name='initial_buy_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fee'), (2, 'Amount')], default=1),
        ),
        migrations.AddField(
            model_name='assetstoken',
            name='labels',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol_id', models.PositiveBigIntegerField(db_index=True)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.assetstoken')),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocol',
                'db_table': 'assets_protocol',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='assetstoken',
            name='games',
            field=models.ManyToManyField(to='assets.AssetsGame'),
        ),
    ]
