# Generated by Django 4.0 on 2024-10-21 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetsgame_assetstoken_epal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetstoken',
            options={'ordering': ('sort', '-created_at'), 'verbose_name': 'Assets Token', 'verbose_name_plural': 'Assets Tokens'},
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='token',
        ),
        migrations.AddField(
            model_name='assetstoken',
            name='epal_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='assetstoken',
            name='protocol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.protocol'),
        ),
        migrations.AddField(
            model_name='assetstoken',
            name='sort',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='protocol',
            name='symbol',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
