# Generated by Django 4.0 on 2024-10-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_protocol_bonding_curve_protocol_day_increase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('open', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('close', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('high', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('low', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('time', models.DateTimeField(db_index=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.protocol')),
            ],
            options={
                'verbose_name': 'Minute Market Data',
                'verbose_name_plural': 'Minute Market Data',
                'db_table': 'assets_minute_market_data',
                'ordering': ('-created_at',),
            },
        ),
    ]
