# Generated by Django 4.0 on 2024-11-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_whitelistaddress'),
        ('assets', '0005_minutemarketdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='bonding_curve',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetstoken')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Position',
                'db_table': 'assets_position',
                'ordering': ('-created_at',),
            },
        ),
    ]
