# Generated by Django 4.0 on 2024-11-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_whitelistaddress'),
        ('assets', '0006_alter_protocol_bonding_curve_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('time', models.DateTimeField()),
                ('hash', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetstoken')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transaction',
                'db_table': 'assets_transaction',
                'ordering': ('-time',),
            },
        ),
    ]
