# Generated by Django 4.0 on 2024-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='bonding_curve',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='day_increase',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='day_trading_volume',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='market_value',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='price',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
