# Generated by Django 4.0 on 2024-11-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_protocol_bonding_curve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
    ]
