# Generated by Django 4.0 on 2024-11-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_position_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstoken',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assetstoken',
            name='labels',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
