# Generated by Django 4.0 on 2024-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_assetstoken_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstoken',
            name='initial_buy_number',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='close',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='high',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='low',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='open',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='volume',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
    ]
