# Generated by Django 4.0 on 2024-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_assetstoken_initial_buy_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='bonding_curve',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='day_increase',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='day_trading_volume',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='market_value',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
    ]
