# Generated by Django 4.0 on 2024-11-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_protocol_bonding_curve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='volume',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
    ]
