# Generated by Django 4.0 on 2024-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_protocol_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstoken',
            name='initial_buy_number',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='close',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='high',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='low',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='open',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='minutemarketdata',
            name='volume',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='bonding_curve',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='day_increase',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='day_trading_volume',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=60),
        ),
    ]
