# Generated by Django 4.0 on 2024-11-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_alter_assetstoken_initial_buy_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='minutemarketdata',
            unique_together={('protocol', 'time')},
        ),
    ]
