# Generated by Django 4.0 on 2024-12-03 11:49

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_minutemarketdata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsgame',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.upload_game_logo),
        ),
    ]
