# Generated by Django 4.0 on 2024-10-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[])),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Basic Info',
                'verbose_name_plural': 'Basic Info',
                'db_table': 'generic_basic_info',
                'ordering': ('type', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_id', models.CharField(max_length=128)),
                ('service', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=200)),
                ('request_at', models.DateTimeField()),
                ('response_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Log',
                'db_table': 'generic_request_log',
            },
        ),
        migrations.CreateModel(
            name='RequestLogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generic.requestlog')),
            ],
            options={
                'verbose_name': 'Request Log Detail',
                'verbose_name_plural': 'Request Log Detail',
                'db_table': 'generic_request_log_detail',
            },
        ),
    ]
