# Generated by Django 4.0 on 2024-10-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rpc_url', models.CharField(blank=True, max_length=255, null=True)),
                ('chain_id', models.CharField(max_length=20, unique=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('block_explorer_url', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('api_token', models.CharField(blank=True, max_length=255, null=True)),
                ('last_page', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Network',
                'db_table': 'wallet_network',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.network')),
            ],
            options={
                'verbose_name': 'Wallet Address',
                'verbose_name_plural': 'Wallet Address',
                'db_table': 'wallet_wallet_address',
                'ordering': ('-created_at',),
                'unique_together': {('network', 'address')},
            },
        ),
    ]
