# Generated by Django 4.0 on 2024-12-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_whitelistaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
