# Generated by Django 4.0 on 2024-10-23 09:38

from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_whitelistaddress'),
        ('assets', '0004_protocol_bonding_curve_protocol_day_increase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetstoken')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
                'db_table': 'social_comment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommentImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to=social.models.upload_comment_img)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.comment')),
            ],
            options={
                'verbose_name': 'Comment Img',
                'verbose_name_plural': 'Comment Img',
                'db_table': 'social_comment_img',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='account.account')),
            ],
            options={
                'verbose_name': 'Fans',
                'verbose_name_plural': 'Fans',
                'db_table': 'social_fans',
                'ordering': ['-created_at'],
                'unique_together': {('account', 'follower')},
            },
        ),
    ]
